### ISSUE TITLE
Scaffolding and Skeleton

### ISSUE THREAD

**Issue by GMancillas9** [basedvegan/ggourmet#1]
Making sure we follow MVC model while still using static (handlebars) and non-static (template) files.

**Comment by GMancillas9** [comment]
@basedvegan, 
I've pushed the MVC structure for our app to the "MVC" branch, please review and approve. 
Then we can pull so we're all working with the updated version and avoid conflicts. 

Important notes and future issues: 

1. Views folder has not been created as that will contain our handlebars files.
2. We need to store our template files in the public folder
3. Package j.son and node_modules and .gitignore are also pending

**Comment by Ernsbecerra88** [comment]
1.-answer: there is a views folder, inside and 2 .handelbars files.

**Comment by Ernsbecerra88** [comment]
2. let me know how this goes @basedvegan @GMancillas9 I dont think I need to do any routing for anything located in public .

**Comment by Ernsbecerra88** [comment]
3.as far as packages i belive we should all npm install mysql express express-handlebars we dont need sequelize as im using a custom ORM .

**Comment by Ernsbecerra88** [comment]
modifing public folder / removing  templates since we are useing handelbars to makeweb site more dynamic.
