### ISSUE TITLE
Back-End Part A

### ISSUE THREAD

**Issue by GMancillas9** [basedvegan/ggourmet#7]
(My SQL Database): Will store customer Name, Phone, E-mail Address, Diet Type - Ernesto

**Comment by Ernsbecerra88** [comment]
its basic and its piggy back from activities but its honest work, still adding final touches.

**Comment by Ernsbecerra88** [comment]
my code broke.

**Comment by GMancillas9** [comment]
We're restarting with sequlelize instead of creating an orm
