### ISSUE TITLE
Handlebars + Template

### ISSUE THREAD

**Issue by GMancillas9** [basedvegan/ggourmet#8]
@Ernsbecerra88 @basedvegan 

1. Npm express-handlebars will generate the views folder and subfolders + the handlebars files
2. We need to store our static template files in the public folder, correct? 
3. Node_modules, package.json: does it matter which of our computers do it locally? I hesitated to push since I'm not sure

**Comment by Ernsbecerra88** [comment]
yes static files are stored in public

**Comment by Ernsbecerra88** [comment]
please clearify question 3.

**Comment by GMancillas9** [comment]
3. I resolved question #3 by running npm install, init, express-handlebars, mysql, and sequelize on my local computer. 

Review this 2nd MVC push to master and let me know if you guys are able to work off of it @Ernsbecerra88  @DennisJMorales @basedvegan

**Comment by GMancillas9** [comment]
Working with templating engine and no static files now
